- name: Create New User and Setup System
  hosts: all
  become: true
  gather_facts: true
  vars:
    username: coding
    userpass: coding
  tasks:
    - name: Ensure user "{{ username }}" exists
      ansible.builtin.user:
        name: '{{ username }}'
        password: "{{ userpass | password_hash('sha512') }}"
        shell: /bin/bash
        update_password: on_create

    - name: Deploy SSH Public Key for "{{ username }}"
      ansible.builtin.authorized_key:
        user: '{{ username }}'
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob: ./keys/*

    - name: Add user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ username }}
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install Docker
      ansible.builtin.package:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pull Docker image
      ansible.builtin.docker_image:
        name: ghcr.io/devopscodingfactory/api_node/api_node:latest
        source: pull

    - name: Run Docker container
      ansible.builtin.docker_container:
        name: api_node
        image: ghcr.io/devopscodingfactory/api_python/api_node:latest
        state: started
        published_ports:
          - "8000:8000"