name: Build, Publish and Deploy

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint
  
  publish:
    runs-on: [ self-hosted, node ]

    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_API_PORT: ${{ secrets.API_PORT }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          file_name: .env
          fail_on_empty: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/devopscodingfactory/api_node/apipokemon_node:${{ github.ref_name }}